name: Latest Blog Post Web
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'
permissions:
      contents: write
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "Blog-Web"
          feed_list: "https://blognivins.netlify.app/index.xml"
          template: "<tr><td>$title</td><td>$url</td></tr>"
